version: '3.8'
services:
  flowyt_db:
    image: postgres:16.1
    container_name: flowyt_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5477:5432'
    networks:
      - flowyt-network

  flowyt_redis:
    image: redis:7.2.3-alpine
    container_name: flowyt_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - flowyt-network

  # api:
  #   build: .
  #   container_name: api
  #   command: ["bash", "/usr/src/app/start.sh"]
  #   ports:
  #     - "7000:7000"
  #   depends_on:
  #     - redis
  #     - db
  #   links:
  #     - db:db
  #     - redis:redis
  #   networks:
  #     - flowyt-network

networks:
  flowyt-network:
    name: flowyt-network
    driver: bridge