# Generated by Django 3.0.3 on 2020-02-07 21:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Workspace Name')),
                ('description', models.TextField(blank=True, help_text='(Opcional)', null=True, verbose_name='Descrição')),
                ('slug', models.SlugField(blank=True, help_text='(Opcional)', null=True, verbose_name='Slug')),
                ('integrations', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='(Opcional)', max_length=255, null=True, verbose_name='Integrações')),
                ('envs', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='(Opcional)', null=True, verbose_name='Environments')),
                ('workspace_color', models.CharField(blank=True, max_length=6, null=True, verbose_name='Workspace Name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Flow Name')),
                ('flow_layout', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Flow Layout')),
                ('flow_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='(Opcional)', null=True, verbose_name='Flow Data')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.Workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
