# Generated by Django 3.0.3 on 2020-02-08 18:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Releases',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Workspace Name')),
                ('description', models.TextField(blank=True, help_text='(Opcional)', null=True, verbose_name='Description')),
            ],
            options={
                'ordering': ['updated_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='flow',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='workspace',
            name='description',
            field=models.TextField(blank=True, help_text='(Opcional)', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='integrations',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='(Opcional)', max_length=255, null=True, verbose_name='Integrations'),
        ),
        migrations.CreateModel(
            name='WorkspaceReleases',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Workspace Name')),
                ('description', models.TextField(blank=True, help_text='(Opcional)', null=True, verbose_name='Description')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.Releases')),
            ],
            options={
                'ordering': ['updated_at'],
            },
        ),
        migrations.AddField(
            model_name='releases',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.Workspace'),
        ),
        migrations.CreateModel(
            name='FlowReleases',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Flow Name')),
                ('flow_layout', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Flow Layout')),
                ('flow_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='(Opcional)', null=True, verbose_name='Flow Data')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.WorkspaceReleases')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
