# Generated by Django 3.0.3 on 2020-02-04 20:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='envs',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='(Opcional)', null=True, verbose_name='Environments'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='integrations',
            field=models.CharField(blank=True, help_text='(Opcional)', max_length=255, null=True, verbose_name='Integrações'),
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Flow Name')),
                ('flow_layout', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Flow Layout')),
                ('flow_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='(Opcional)', null=True, verbose_name='Flow Data')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.Workspace')),
            ],
        ),
    ]
