# Generated by Django 3.0.3 on 2020-02-21 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="environment", unique_together={("name", "workspace")},),
        migrations.AlterUniqueTogether(name="flow", unique_together={("name", "workspace")},),
        migrations.AlterUniqueTogether(name="functionfile", unique_together={("name", "workspace")},),
        migrations.AlterUniqueTogether(name="integration", unique_together={("name", "workspace")},),
        migrations.AlterUniqueTogether(name="release", unique_together={("name", "workspace")},),
        migrations.AlterUniqueTogether(name="workspace", unique_together={("name", "team")},),
    ]
