# Generated by Django 3.0.4 on 2020-03-11 00:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='safe_mode',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default='{"enable": true, "safe_time": 10}', help_text='(Opcional)', null=True, verbose_name='Environment variables'),
        ),
        migrations.AlterField(
            model_name='environmentrelease',
            name='safe_mode',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default='{"enable": true, "safe_time": 10}', help_text='(Opcional)', null=True, verbose_name='Environment variables'),
        ),
    ]
