# Generated by Django 3.0.3 on 2020-02-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="functionfile",
            name="function_data",
            field=models.TextField(
                blank=True,
                help_text="(Opcional)",
                null=True,
                verbose_name="Function data",
            ),
        ),
        migrations.AlterField(
            model_name="functionfilerelease",
            name="function_data",
            field=models.TextField(
                blank=True,
                help_text="(Opcional)",
                null=True,
                verbose_name="Function data",
            ),
        ),
    ]
