# Generated by Django 3.0.3 on 2020-02-09 22:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flow",
            name="flow_layout",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True,
                help_text="(Opcional)",
                null=True,
                verbose_name="Flow Layout",
            ),
        ),
    ]
