# Generated by Django 3.0.3 on 2020-02-21 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0002_auto_20200221_0311"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="route", unique_together={("path", "method", "workspace")},),
    ]
