# Generated by Django 3.0.3 on 2020-02-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_auto_20200209_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='active',
            field=models.BooleanField(default=False, help_text='(Opcional)'),
        ),
    ]
