# Generated by Django 3.0.4 on 2020-03-24 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0002_auto_20200323_1856"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="language",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="workspaces.Language"
            ),
        ),
    ]
