# Generated by Django 3.0.3 on 2020-02-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_auto_20200204_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='flow',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Atualizado em'),
        ),
    ]
