# Generated by Django 3.0.3 on 2020-02-08 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_auto_20200208_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flowreleases',
            old_name='workspace',
            new_name='workspace_release',
        ),
    ]
