# Generated by Django 3.0.3 on 2020-03-02 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0002_auto_20200218_2259"),
        ("workspaces", "0003_auto_20200221_0358"),
    ]

    operations = []
