# Generated by Django 3.0.3 on 2020-02-05 18:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_auto_20200204_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='integrations',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='(Opcional)', max_length=255, null=True, verbose_name='Integrações'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='Atualizado em'),
        ),
    ]
