# Generated by Django 3.0.4 on 2020-03-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0003_auto_20200324_2148"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="language",
            field=models.CharField(max_length=100, verbose_name="Language"),
        ),
        migrations.AlterField(
            model_name="workspacerelease",
            name="workspace_color",
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name="Workspace Color"),
        ),
    ]
