# Generated by Django 3.0.4 on 2020-04-12 00:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0004_auto_20200325_2326"),
    ]

    operations = [
        migrations.AlterField(
            model_name="environment",
            name="safe_mode",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, help_text="(Opcional)", null=True, verbose_name="Safe Mode"
            ),
        ),
    ]
