# Generated by Django 3.0.3 on 2020-02-14 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_auto_20200214_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='functionfilerelease',
            name='workspace',
        ),
    ]
