# Generated by Django 3.0.3 on 2020-03-03 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0004_merge_20200302_1952"),
        ("workspaces", "0004_merge_20200303_0159"),
    ]

    operations = []
