# Generated by Django 3.0.3 on 2020-02-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_auto_20200205_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='workspace_color',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Workspace Name'),
        ),
    ]
