# Generated by Django 3.0.3 on 2020-03-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0005_merge_20200303_0320"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="workspace_color",
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name="Workspace Color"),
        ),
    ]
