# Generated by Django 3.0.4 on 2020-05-28 18:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_auto_20200412_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Integration Name')),
                ('description', models.TextField(blank=True, help_text='(Opcional)', null=True, verbose_name='Description')),
                ('integration_variables', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='(Opcional)', null=True, verbose_name='Environment variables')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='integrationrelease',
            name='name',
        ),
        migrations.AlterUniqueTogether(
            name='integration',
            unique_together={('workspace',)},
        ),
        migrations.RemoveField(
            model_name='integration',
            name='name',
        ),
        migrations.AddField(
            model_name='integration',
            name='integration_list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workspaces.IntegrationList'),
            preserve_default=False,
        ),
    ]
