# Generated by Django 3.0.3 on 2020-02-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_remove_functionfilerelease_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionfilerelease',
            name='description',
            field=models.TextField(blank=True, help_text='(Opcional)', null=True, verbose_name='Description'),
        ),
    ]
