# Generated by Django 3.0.3 on 2020-03-03 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0006_auto_20200303_0346"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment", name="can_delete", field=models.BooleanField(default=True),
        ),
    ]
