# Generated by Django 3.0.4 on 2020-05-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0006_auto_20200528_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationlist',
            name='integration_key',
            field=models.CharField(default=None, max_length=255, verbose_name='Integration Key'),
            preserve_default=False,
        ),
    ]
