# Generated by Django 3.0.3 on 2020-02-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0006_functionfilerelease_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
