# Generated by Django 3.0.3 on 2020-03-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0007_environment_can_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="safe_mode",
            field=models.BooleanField(default=True, help_text="(Default true)"),
        ),
    ]
