# Generated by Django 3.0.3 on 2020-02-15 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0008_auto_20200215_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionfile',
            name='description',
            field=models.TextField(blank=True, help_text='(Opcional)', null=True, verbose_name='Description'),
        ),
    ]
