# Generated by Django 3.0.4 on 2020-03-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0008_environment_safe_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacerelease',
            name='workspace_color',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Workspace Color'),
        ),
    ]
