# Generated by Django 3.0.7 on 2020-06-06 19:28

from django.db import migrations, models
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0008_monitor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="environment",
            name="environment_variables",
            field=utils.fields.JSONEncryptedField(
                blank=True, help_text="(Opcional)", null=True, verbose_name="Environment variables"
            ),
        ),
        migrations.AlterField(
            model_name="environmentrelease",
            name="environment_variables",
            field=utils.fields.JSONEncryptedField(
                blank=True, help_text="(Opcional)", null=True, verbose_name="Environment variables"
            ),
        ),
        migrations.AlterField(
            model_name="integrationlist",
            name="integration_variables",
            field=utils.fields.JSONEncryptedField(
                blank=True, help_text="(Opcional)", null=True, verbose_name="Environment variables"
            ),
        ),
        migrations.AlterField(
            model_name="integrationrelease",
            name="integration_variables",
            field=utils.fields.JSONEncryptedField(
                blank=True, help_text="(Opcional)", null=True, verbose_name="Environment variables"
            ),
        ),
        migrations.AlterField(
            model_name="monitor", name="password", field=models.CharField(max_length=255, verbose_name="Host"),
        ),
    ]
