# Generated by Django 3.0.3 on 2020-02-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0009_functionfile_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowrelease',
            name='workspace',
        ),
        migrations.AddField(
            model_name='flow',
            name='description',
            field=models.TextField(blank=True, help_text='(Opcional)', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='flowrelease',
            name='description',
            field=models.TextField(blank=True, help_text='(Opcional)', null=True, verbose_name='Description'),
        ),
    ]
