# Generated by Django 3.0.4 on 2020-03-10 23:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0009_auto_20200306_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='release',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='environment',
            name='safe_mode',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='(Opcional)', null=True, verbose_name='Environment variables'),
        ),
    ]
