# Generated by Django 3.0.4 on 2020-03-10 23:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0010_auto_20200310_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='safe_mode',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict(enable=True, safe_time=10), help_text='(Opcional)', null=True, verbose_name='Environment variables'),
        ),
    ]
