# Generated by Django 3.0.3 on 2020-02-15 19:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0010_auto_20200215_0440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='Atualizado em')),
                ('path', models.CharField(max_length=255, verbose_name='Path')),
                ('method', models.CharField(choices=[('GET', 'Get'), ('POST', 'Post'), ('PUT', 'Put'), ('DELETE', 'Delete'), ('PATCH', 'Patch'), ('TRACE', 'Trace'), ('OPTIONS', 'Options'), ('CONNECT', 'Connect')], max_length=10, verbose_name='HTTP Method')),
                ('description', models.TextField(blank=True, help_text='(Opcional)', null=True, verbose_name='Description')),
                ('active', models.BooleanField(default=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.Flow')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.Workspace')),
            ],
            options={
                'ordering': ['path'],
            },
        ),
    ]
