# Generated by Django 3.0.3 on 2020-02-15 20:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0011_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentrelease',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workspaces.Environment'),
        ),
        migrations.AlterField(
            model_name='flowrelease',
            name='flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workspaces.Flow'),
        ),
        migrations.AlterField(
            model_name='functionfilerelease',
            name='function_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workspaces.FunctionFile'),
        ),
        migrations.AlterField(
            model_name='integrationrelease',
            name='integration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workspaces.Integration'),
        ),
        migrations.AlterField(
            model_name='workspacerelease',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workspaces.Workspace'),
        ),
        migrations.CreateModel(
            name='RouteRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='Atualizado em')),
                ('path', models.CharField(max_length=255, verbose_name='Path')),
                ('method', models.CharField(choices=[('GET', 'Get'), ('POST', 'Post'), ('PUT', 'Put'), ('DELETE', 'Delete'), ('PATCH', 'Patch'), ('TRACE', 'Trace'), ('OPTIONS', 'Options'), ('CONNECT', 'Connect')], max_length=10, verbose_name='HTTP Method')),
                ('description', models.TextField(blank=True, help_text='(Opcional)', null=True, verbose_name='Description')),
                ('active', models.BooleanField(default=True)),
                ('flow_release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.FlowRelease')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.Release')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workspaces.Route')),
                ('workspace_release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.WorkspaceRelease')),
            ],
            options={
                'ordering': ['path'],
            },
        ),
    ]
