# Generated by Django 3.0.4 on 2020-03-10 23:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0011_auto_20200310_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentrelease',
            name='debug',
            field=models.BooleanField(default=False, help_text='(Default false)'),
        ),
        migrations.AddField(
            model_name='environmentrelease',
            name='safe_mode',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={'enable': True, 'safe_time': 10}, help_text='(Opcional)', null=True, verbose_name='Environment variables'),
        ),
    ]
