# Generated by Django 3.0.3 on 2020-02-15 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0013_remove_workspace_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspacerelease',
            name='slug',
        ),
    ]
