# Generated by Django 3.0.7 on 2020-06-06 20:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0014_auto_20200606_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='environment_variables',
            field=models.TextField(blank=True, help_text='(Opcional)', null=True, verbose_name='Environment variables'),
        ),
        migrations.AlterField(
            model_name='environmentrelease',
            name='environment_variables',
            field=models.TextField(blank=True, help_text='(Opcional)', null=True, verbose_name='Environment variables'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='integration_variables',
            field=models.TextField(blank=True, help_text='(Opcional)', null=True, verbose_name='Environment variables'),
        ),
        migrations.AlterField(
            model_name='integrationlist',
            name='integration_variables',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='(Opcional)', null=True, verbose_name='Environment variables'),
        ),
        migrations.AlterField(
            model_name='integrationrelease',
            name='integration_variables',
            field=models.TextField(blank=True, help_text='(Opcional)', null=True, verbose_name='Environment variables'),
        ),
    ]
