# Generated by Django 3.0.7 on 2020-06-06 20:31

from django.db import migrations, models
import django.db.models.deletion
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0018_auto_20200606_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitor',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='database',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='host',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='port',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='user',
        ),
        migrations.AddField(
            model_name='monitor',
            name='environment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workspaces.Environment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitor',
            name='monitor_database_type',
            field=models.CharField(default=None, max_length=255, verbose_name='Monitor database type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitor',
            name='monitor_variables',
            field=utils.fields.JSONEncryptedField(blank=True, help_text='(Opcional)', null=True, verbose_name='Environment variables'),
        ),
    ]
