# Generated by Django 3.0.7 on 2020-06-07 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0019_auto_20200606_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='environment_variables',
            field=models.TextField(blank=True, help_text='(Opcional)', null=True, verbose_name='Environment variables'),
        ),
    ]
