# Generated by Django 3.0.7 on 2020-06-08 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0022_auto_20200607_2255"),
    ]

    operations = [
        migrations.RemoveField(model_name="monitor", name="environment",),
        migrations.AddField(
            model_name="monitor",
            name="workspace",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="workspaces.Workspace"),
            preserve_default=False,
        ),
    ]
