# Generated by Django 4.1.4 on 2024-01-19 01:22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.teams.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, null=True, verbose_name="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, null=True, verbose_name="Atualizado em"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, help_text="(Opcional)", null=True)),
                ("can_delete", models.BooleanField(default=True)),
                ("organization", models.CharField(max_length=255, verbose_name="Organization")),
                (
                    "subdomain",
                    models.CharField(
                        db_index=True, max_length=500, null=True, unique=True, verbose_name="Subdomain"
                    ),
                ),
                ("is_personal", models.BooleanField(default=False, verbose_name="Is Personal Team?")),
                ("members", models.ManyToManyField(related_name="teams", to=settings.AUTH_USER_MODEL)),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "team",
                "verbose_name_plural": "teams",
            },
        ),
        migrations.CreateModel(
            name="TeamInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, null=True, verbose_name="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, null=True, verbose_name="Atualizado em"
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("code", models.CharField(default=apps.teams.models.generate_invite_code, max_length=25)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "PENDING"),
                            (1, "ACCEPTED"),
                            (2, "DECLINED"),
                            (4, "EXPIRED"),
                            (5, "REMOVED"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitations_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="teams.team"
                    ),
                ),
            ],
            options={
                "verbose_name": "team invitation",
                "verbose_name_plural": "team invitations",
                "unique_together": {("email", "code")},
            },
        ),
    ]
