# Generated by Django 3.0.4 on 2020-03-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_teaminvitation_can_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaminvitation',
            name='can_delete',
        ),
        migrations.AddField(
            model_name='team',
            name='can_delete',
            field=models.BooleanField(default=True),
        ),
    ]
