# Generated by Django 3.0.4 on 2020-03-17 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0004_auto_20200316_1756"),
    ]

    operations = [
        migrations.AddField(
            model_name="teaminvitation",
            name="team",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="teams.Team"
            ),
        ),
    ]
