# Generated by Django 3.0.4 on 2020-03-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0006_auto_20200324_2148"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="sub_domain_url",
            field=models.URLField(
                db_index=True, max_length=500, null=True, unique=True, verbose_name="Sub Domain"
            ),
        ),
        migrations.DeleteModel(name="SubDomain",),
    ]
