# Generated by Django 3.0.4 on 2020-03-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0007_auto_20200325_0232"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="is_personal",
            field=models.BooleanField(default=True, verbose_name="Is Personal Team?"),
        ),
    ]
