# Generated by Django 3.0.4 on 2020-03-25 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0009_auto_20200325_0324"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="description",
            field=models.TextField(blank=True, help_text="(Opcional)", null=True),
        ),
    ]
