# Generated by Django 3.0.4 on 2020-03-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0010_auto_20200325_0326"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="organization",
            field=models.CharField(max_length=255, verbose_name="Organization"),
        ),
    ]
