# Generated by Django 3.0.4 on 2020-03-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0012_auto_20200326_1211"),
    ]

    operations = [
        migrations.RemoveField(model_name="team", name="subdomain_url",),
        migrations.AddField(
            model_name="team",
            name="subdomain",
            field=models.CharField(
                db_index=True, max_length=500, null=True, unique=True, verbose_name="Subdomain"
            ),
        ),
    ]
