# Generated by Django 4.1.4 on 2024-01-19 01:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='Atualizado em')),
                ('name', models.CharField(blank=True, help_text='(Opcional)', max_length=100, null=True, verbose_name='Name')),
                ('host', models.CharField(max_length=255, verbose_name='Host')),
                ('secret_token', models.CharField(max_length=255, verbose_name='Secret')),
                ('description', models.TextField(blank=True, help_text='(Opcional)', null=True, verbose_name='Description')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_hosts', to='teams.team')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
