# Generated by Django 3.0.3 on 2020-02-20 17:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Host",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        null=True,
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Atualizado em",
                    ),
                ),
                ("host", models.CharField(max_length=255, verbose_name="Host")),
                (
                    "secret_token",
                    models.CharField(max_length=255, verbose_name="Secret"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="(Opcional)",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
            ],
            options={"ordering": ["created_at"],},
        ),
    ]
