# Generated by Django 3.0.3 on 2020-03-03 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_auto_20200303_0159"),
        ("hosts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="host",
            name="team",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="teams.Team"
            ),
        ),
    ]
